version: '3.9'
services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    container_name: dealers-bird-db
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_DATABASE
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - Dealers-Bird-Network

  adminer:
    image: adminer
    container_name: dealers-bird-db-adminer
    ports:
      - 8080:$ADMINER_PORT
    depends_on:
      - db
    networks:
      - Dealers-Bird-Network

networks:
  Dealers-Bird-Network: 

volumes:
  mysql-data:
